### ISSUE TITLE
bad validation of defaultValue

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-microprofile#143]
on this:

```
@ConfigProperty(name = "qilt.myemails", defaultValue = "")
    List<String> myEmails;
```

I get error: `'' does not match the expected type of 'List<String>'.microprofile-config(DEFAULT_VALUE_IS_WRONG_TYPE)`

That does not make sense IMO as the defaultValue is supposed to be a String which then gets mapped to a list. Which "" is an empty list.

**Comment by fbricon** [comment]
It's missing the conversion mechanism from String to List

**Comment by angelozerr** [comment]
Indeed it is a annoying problem. We need to improve our validator with this usecase.

**Comment by datho7561** [comment]
> That does not make sense IMO as the defaultValue is supposed to be a String which then gets mapped to a list. Which "" is an empty list.

I am working on implementing the array/list conversion mechanism, and it looks like config values can't be an empty list, i.e. if you set the `defaultValue` as `""` then `smallrye-config` doesn't recognize this as the value being set, so there is no way to provide an empty list.
