### ISSUE TITLE
Error: "Request textDocument/completion failed" on 0.7.0 update

### ISSUE THREAD

**Issue by iammohitsakhuja** [redhat-developer/vscode-microprofile#155]
Hi, ever since the extension got updated to version `0.7.0`, I have started getting the following error while normally editing the code for a Java project:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/30660843/230334640-68edf766-b4ae-4dd8-bf8f-4d3bc432c07a.png">

Here's the log dump:
```
[Error - 2:52:01 PM] Request textDocument/completion failed.
  Message: Request microprofile/java/completion failed with message: Cannot invoke "org.eclipse.jdt.core.dom.Type.getStartPosition()" because the return value of "org.eclipse.jdt.core.dom.MethodDeclaration.getReturnType2()" is null
  Code: -32603 
```

Is this a regression? Or should I update something else on my system?

I'm not sure how the language server itself works, whether it uses the system JDK or not, but here's some more information (dunno how useful it is):
* OS: macOS Ventura 13.3
* JDK: Temurin JDK 17.0.6

Please let me know if there's some way I can help further. The error pops up too frequently, enough for me to have to disable the extension in the meantime.

**Comment by fbricon** [comment]
Looks like a regression. Could you share your project or a sample project reproducing the issue?

@angelozerr looks like we don't have a way to disable microprofile completion, that's unfortunate.

**Comment by angelozerr** [comment]
> Looks like a regression.

I think so

>  Could you share your project or a sample project reproducing the issue?

@iammohitsakhuja please do that.

> @angelozerr looks like we don't have a way to disable microprofile completion, that's unfortunate.

I suppose you wish to do that when there is a bug like this issue. I'm not sure that it is a good idea, we need to fix issues instead of hiding it. More if we want to do that, we should do that for another operation like hover, etc

**Comment by iammohitsakhuja** [comment]
Hi, thanks for replying! I'm sorry for the delay – I couldn't find the time to reproduce it properly before as this was occurring in a work project, and for obvious reasons, I cannot share that.

However, I have reproduced the same on a sample project, and it seems to be related to the usage of Lombok. I am not entirely sure where the fault lies as Lombok support (I am using VSCode for this) is coming from [Language Support for Java](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension.

Here's a sample project for the same: https://github.com/iammohitsakhuja/vscode-microprofile-155-sample

The only helpful file regarding this is `EntityWithLombok.java`. Here are the steps to reproduce this error:
1. Try adding, say `@Serial` annotation above the `serialVersionUID` field. The extension should produce an error.
2. Doing the same in the `EntityWithoutLombok.java` file does not produce an error.

**Comment by angelozerr** [comment]
Thanks @iammohitsakhuja for your info.

If I remember with Lonbok, JDT generate sepcials files, it is perhaps because of this generated field that we have this error and we should filter it.

@datho7561 could you try the sample to try to reproduce it, thanks.

**Comment by datho7561** [comment]
Yes, I can investigate it

**Comment by datho7561** [comment]
It looks like the root cause of this issue is that Lombok includes generated methods in the AST. We should ignore those. I'm a bit stuck currently, as the Eclipse debugger reports a public field `$isGenerated` on all `ASTNode` to check if the node was generated by Project Lombok, but the source file for `ASTNode` doesn't list this field.

**Comment by datho7561** [comment]
> it is not a regression

In the previous version, this Exception wouldn't happen, since we didn't support context-aware snippets.

> I did that for codelens at

Yes, I ended up copying the solution from there. Thanks!

**Comment by angelozerr** [comment]
Thanks so much @datho7561 !

**Comment by iammohitsakhuja** [comment]
Thanks @datho7561 ! Just tested it, works flawlessly. 🥳

**Comment by angelozerr** [comment]
Great job @datho7561 !
