### ISSUE TITLE
Allow to register patterns to exclude unknown properties validation

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-microprofile#22]
https://issues.redhat.com/browse/FUSETOOLS2-710

for instance, when there is the Language Support for Apache Camel, I would like to not have warnings for properties having the pattern `camel.*`

To see the current issue,
- import https://github.com/apache/camel-quarkus/tree/master/integration-tests/main-xml-io
- add to the pom
```
<repositories>
	<repository>
		<id>apache.snapshots</id>
		<name>Apache Development Snapshot Repository</name>
		<url>https://repository.apache.org/content/repositories/snapshots/</url>
		<releases>
			<enabled>false</enabled>
		</releases>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```
- open the application.properties file

![Screenshot from 2020-09-21 13-20-50](https://user-images.githubusercontent.com/1105127/93760982-4f187a00-fc0d-11ea-828a-f53d3c67ce60.png)

the curretn solution is that the users is to use the quickfix to ignore warnings on camel.* which is adding a setting to ignore them.

**Comment by angelozerr** [comment]
To fix this issue we should give the capability to declare the ignore properties with:

 * package.json. It will work only with vscode.
 * or with a new Java SPI extension to register a JSON which will declare the properties to ignore. The benefit with that it will work with any LSP client.

@fbricon what do you think about that?

**Comment by fbricon** [comment]
or, we could have a better detection mechanism, to know that camel properties are available, and then propose them for completion

**Comment by angelozerr** [comment]
If I understand correctly your suggestion you would like to extend LSP4MP with a `CamelPropertiesProvider` to compute camel properties from the Java project.

 It means that vscode-camel should switch to LSP4MP to compute camel properties, I'm not sure that it's a good idea, because it means that for no camel-quarkus, it will not work (because the project is not a microprofile project).

For me the usecase is that vscode-camel can compute camel properties and don't want to delegate those camel properties to LSP4MP, in other words vscode-camel want to ignore validation for camel.* properties.

**Comment by apupier** [comment]
> For me the usecase is that vscode-camel can compute camel properties and don't want to delegate those camel properties to LSP4MP, in other words vscode-camel want to ignore validation for camel.* properties.

this seems to better match what we need.
We effectively provide the completion also for non-Quarkus project.

**Comment by angelozerr** [comment]
> this seems to better match what we need.

Glad we are agree :)

Now the question is how to manage that : 

 * on vscode-microprofile (only vscode will work)
 * on language server LSPMP. All LSP client (like vscode, Eclipse IDE) will benefit with ignore validation. 

@apupier do you need this ignore validation on vscode only, or with other LSP client?

**Comment by apupier** [comment]
> do you need this ignore validation on vscode only, or with other LSP client?

priority is on VS Code for sure but i would prefer with other LSP client.
What is the difference of complexity?

**Comment by angelozerr** [comment]
> What is the difference of complexity?

vscode provides an API to read descriptor from package.json, so I would say that it's a standard mean to declare some behaviors. From your point, you will need to develop a lsp4mp-camel.jar which embeds your JSON  validation rules.

For LSP4MP, it will require to develop some code which merges those settings but it's not a big deal. So I think we should manage that in LSP4MP.

@apupier @fbricon if you like the idea, I will create an issue in LSP4MP.

**Comment by apupier** [comment]
that's fine for me.

**Comment by angelozerr** [comment]
I close this issue for https://github.com/eclipse/lsp4mp/issues/95
