### ISSUE TITLE
Remove quarkus-properties language

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-microprofile#3]
The goal of this issue os to remove quarkus-properties language declaration in https://github.com/redhat-developer/vscode-microprofile/pull/1/files/ab9336fea779e140cf9dd4afa0521c016778d859#r455636547 which is used to

 *  bind quarkus application.properties to the MicroProfile LS
 * bind textmate grammar for application.properties file

We need to remove quarkus-properties and have just `microprofile-properties` language, but in vscode-quarkus we need `quarkus-properties`, so it means that:

 * vscode-microprofile must provide a documentSelector extensions to declare in `package.json` of some extensions (ex: vscode-quarkus) the following document selector:

```json
"contributes": 
  "microprofile":
     "documentSelector":  
[
  { scheme: 'file', language: 'quarkus-properties' }
]
```

After that we could remove https://github.com/redhat-developer/vscode-microprofile/pull/1#pullrequestreview-449666195 and search compute documentSelector my merging the microprofile documentSelector with documentSelector coming from extension (like vscode-quarkus)

 * how to bind the textmate grammar from vscode-microprofile to the quarkus-properties language coming from vscode-quarkus? @xorye have you some idea? When we will find a solution, we will able to to remove https://github.com/redhat-developer/vscode-microprofile/pull/1/files/ab9336fea779e140cf9dd4afa0521c016778d859#r455641270

**Comment by xorye** [comment]
> how to bind the textmate grammar from vscode-microprofile to the quarkus-properties language coming from vscode-quarkus? @xorye have you some idea?

Yes, that is possible. On the vscode-quarkus side: https://github.com/redhat-developer/vscode-quarkus/pull/294/files the properties grammar was removed, and now it depends on vscode-microprofile's properties grammar.
