### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RamadaniHadi** [redhat-developer/vscode-microprofile#48]
- Issue Type: `Performance`
- Extension Name: `vscode-microprofile`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT ia32 6.1.7601`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\user\AppData\Local\Temp\redhat.vscode-microprofile-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by fbricon** [comment]
Maybe attach your redhat.vscode-microprofile-unresponsive.cpuprofile.txt
Also try to take a threaddump of your the Java language server processes.
From a terminal, identify the processes with `jps` (or `jps -v`). The interesting once are "MicroProfileServerLauncher" and "org.eclipse.equinox.launcher*.jar", then `jstack <PID>` to get a thread dump

**Comment by angelozerr** [comment]
@RamadaniHadi  could you attach please your `redhat.vscode-microprofile-unresponsive.cpuprofile.txt`?

**Comment by angelozerr** [comment]
None answer, I close this issue. @RamadaniHadi if you can reproduce the problem please give us more informations. Thanks!
