### ISSUE TITLE
Update @redhat-developer/vscode-redhat-telemetry to 0.1.1

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-microprofile#55]
This removes the dependency to vscode-commons.

See https://github.com/redhat-developer/vscode-redhat-telemetry#add-the-below-code-to-your-extensionts for instructions on how to implement this change.

~~Note that `redhat.telemetry.enabled` doesn't need to be added to the `package.json`, since it will be contributed by `vscode-java`.~~ See note from Fred

**Comment by fbricon** [comment]
no ETA on java telemetry rollout, until then you should still register redhat.telemetry.enabled
