### ISSUE TITLE
Add support for `shouldServerExitOnShutdown` capability

### ISSUE THREAD

**Issue by AlexXuChen** [redhat-developer/vscode-microprofile#69]
As per https://github.com/redhat-developer/vscode-microprofile/pull/68#issuecomment-907213637, there should be support for the capability, meaning the language server shuts down when shutdown is received instead of when exit is received.

**Comment by rgrunber** [comment]
I don't yet know why, but when I test this in an extension host, the MicroProfile language server shuts down immediately on exit, on the latest (vscode-languageclient 0.7.0) branch. I'll try investigating further.
