### ISSUE TITLE
application.properties autocomplete does not work in VS Code Insiders 

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-developer/vscode-microprofile#81]
I was trying out VS Code Insiders to workaround https://github.com/redhat-developer/vscode-quarkus/issues/401 and realised that completion does not work on my application.properties file. 

VS Code Insiders version : Version: 1.61.0-insider (Universal)

**Comment by angelozerr** [comment]
@sebastienblanc you need to install vscode-microprofile https://download.jboss.org/jbosstools/vscode/snapshots/vscode-microprofile/?C=M;O=D
